# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            Rails Taichung
tagline:          '成群、程設、乘就'
description:      '一個人練功太苦悶，一群人聚會有神助'
url:              https://rails-taichung.com
baseurl:          /

author:
  name:           'Rails Taichung'
  url:            https://rails-taichung.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://railstaichung.github.com/
